### ISSUE TITLE
router is not intercepting messages.. namespace specific problem

### ISSUE THREAD

**Issue by rahpuser** [fullstackers/socket.io-events#13]
I'm trying to configure this library in my app. The configuration is like the following:

``` javascript
var router = require('socket.io-events')();
router.on(function(socket, args, next){
  console.log('the middleware...');
  // next();
});

var server = http.Server(app);
var io = IO(server);
io.use(passportSocketIo.authorize({
  cookieParser: cp,
  key: config.cookieKey,        // the name of the express cookie 
  secret:      config.sessionSecret,        // the session_secret to parse the cookie
  store:       mStore,                  // mongo session storage
  success:     onAuthorizeSuccess,          // *optional* callback on success
  fail:        onAuthorizeFail,             // *optional* callback on fail/error
}));

io.use(router);
app.io=io;
server.listen(config.port);
```

As you can see, I'm using express and also I'm using passportSocketio to authorize socket connections, but I don't know why the router.on function is not working.. no console.log is logged and also my messages arrive directly with my 'method'.

Am I doing something wrong in this configuration ?

**Comment by NathanGRomano** [comment]
I am looking into it

**Comment by NathanGRomano** [comment]
Try using version 0.4.2.

**Comment by NathanGRomano** [comment]
I recently published 0.4.6.

**Comment by rahpuser** [comment]
Ok I was about to tell that I just tested in 0.4.2 and is still failing.. let me try the new 0.4.6.. thanks by the way..

**Comment by NathanGRomano** [comment]
I also noticed that you are NOT calling "next", next will give back control to your socket io handlers on the sockets.

``` javascript
router.on(function (sock, args, next) {
  // do some middleware
  next()
});

io.on('connect', function (sock) {
  sock.on('some method', function someCustomHandler () {
   //do something specific
  });
});
```

You can also consume the message so `someCustomHandler` is **not** called.

``` javascript
router.on(function (sock, args, next) {
  // do some middleware
  next()
});

router.on('some custom method', function (sock, args, next) {
  sock.emit('i consumed this event');
  // by doing the sock.emit here the "someCustomHandler" attached to the socket won't be called.
});

io.on('connect', function (sock) {
  sock.on('some method', function someCustomHandler () {
   //do something specific
  });
});
```

**Comment by NathanGRomano** [comment]
what happens when you remove the passport middleware and isolate it down?

**Comment by rahpuser** [comment]
yes, I'm not calling next, I want to stop the propagation but in fact I'm not even getting the console.log('middleware..');.. I always get my socket method.. I already try the 0.4.6, let me try without passport.socketio.. and I will let you know.

Thanks

Edit: I just remember I'm using namespaces to send events.. are those kind of events supported ?

**Comment by rahpuser** [comment]
crap.. sorry if I made you lose your time, I just added the router to the namespace and is working right now..

Thanks, great library.

**Comment by NathanGRomano** [comment]
Glad to help!

**Comment by brucou** [comment]
Hi to both of you, I think I have a similar problem with namespaces. I am using socket.io-events in conjunction with data.io which uses namespaces. Basically if I remove the namespace from the data.io code it works, when I add it back, it does not. I was wondering what it is that you did to add the router to the namespace.

**Comment by brucou** [comment]
Ok I did something like io.of('namespace').use(router) and that seemed to solve the problem (turns out this library does not work well with data.io but that is an unrelated issue). It would be nice to add this to the documentation of this wonderful library. As a suggestion request, there could be an option to also use a wildcard mechanism for the namespace but I guess it is a less frequent use case.

**Comment by NathanGRomano** [comment]
Sure I can take a look at it and and see what I can I do.
