### ISSUE TITLE
 Patch version update should not break API

### ISSUE THREAD

**Issue by mauron85** [fullstackers/socket.io-events#14]
API should stay consistent when doing only patch.

Result of  test following code:

```
function handler (socket, posString, data, callback) {
            socket.broadcast
                .in('courier:' + userId)
                .emit('position:update', {
                    userId: userId,
                    coords: coords
                });

}
```

v.0.4.4 - OK
v.0.4.5 - OK
v.0.4.6 - error: TypeError: Cannot call method 'in' of undefined (meaning socket doesn't have property broadcast anymore)

**Comment by NathanGRomano** [comment]
I will get that resolved. thanks!
