### ISSUE TITLE
Concurrent requests might be lost

### ISSUE THREAD

**Issue by FredericHeem** [fullstackers/socket.io-events#5]
When multiple requests are sent to the socket.io server, some of them might be lost in the onRoute function, depending on the timing. It happens when some middleware functions are asynchronous. 
In the step function, it returns immediately when socket.emit.done is true, this is where the requests are lost. A fix for this issue is not obvious without breaking the API.
Any thought ?

**Comment by NathanGRomano** [comment]
I just woke up let me run a test.

**Comment by NathanGRomano** [comment]
I added a test in spec-e2e/routing-spec.coffee.  It seems to pass.  Do you have any example?

**Comment by FredericHeem** [comment]
Unfortunately, I do only have a private example, writing a specific test case would be too time consuming. 
Moreover, the issue is really time sensitive, most of the time it works, sometimes it doesn't. 
I ended up writing a stripped down version of the router, without regex and with a different api, splitting args in eventName and data.

**Comment by NathanGRomano** [comment]
You can try using "switched" I plan to update socket io evtents to use it

**Comment by NathanGRomano** [comment]
I figured out a solution to prevent this issue.  It will take maybe a day or so.  I will let you know when it is resolved and maybe you will try to use it again.

**Comment by paulforbes42** [comment]
Thank you for making us aware of this issue.  Any potential of lost data is a high priority for us to get resolved.  Once this is fixed we intended to have a test for this specific issue to ensure it remains resolved going forward.  Also, I realize this is a time sensitive issue for you, but any additional examples you can provide may help us with a speedy resolution.  As Nathan mentioned he has identified a fix for the issue, so, we'll keep you up-to-date as we continue to develop the bug fix.  Thanks again!

**Comment by NathanGRomano** [comment]
@FredericHeem I think I have resolved the issue

**Comment by NathanGRomano** [comment]
The socket.io Socket instance's emit was being manipulated which prevented other events happening concurrently from being processed.  The socket.io socket instance is now wrapped in a proxy object.  The proxy object is manipulated now instead of the actual socket.io Socket instance

**Comment by NathanGRomano** [comment]
I just published the new version

**Comment by FredericHeem** [comment]
To reproduce the issue:
On the client side, as soon as the socket is connected, send several requests, in my case this is done by registering a callback with the browserified nodejs event emitter.
On the server side, use asynchronous middleware function e.g getting authentication token with redis.
By the way, the problem was more frequent with Firefox rather than Chrome.
Hope it helps writing a test case.

**Comment by NathanGRomano** [comment]
Maybe you can share a snippet of your auth token with redis.  I implemented
an example with your specs but was able to get all the events.

**Comment by NathanGRomano** [comment]
Have you had a chance to try out the new version?

**Comment by NathanGRomano** [comment]
@FredericHeem any update?
