### ISSUE TITLE
callback support

### ISSUE THREAD

**Issue by shopapps** [fullstackers/socket.io-events#7]
Hi,  does the router support a socket.io callback at all?

e.g. a client emits:

CLIENT:
this.socket.emit('test', {'token': access_token}, function(data){
    // do stuff with the returned data
});

and i am trying to write a server side middleware that intercepts every communication and checks the token (for expirey / tampering etc) 

so on the server side I have:  

SERVER:
router.on('*', socketAuth.authCheckB);

where socketAuth is my middleware:

SERVER:
Mod.prototype.authCheckB = function(socket, args, next) {
   // check the token exists and is valid..  if it's not emit back to the callback
  //  but don't know how to find the callback here???  :-( 
};

Thanks.

Paul.

**Comment by NathanGRomano** [comment]
I could be wrong, but I believe your callback is in `args`.

['some event', 'some data', yourCallbackFunction]

**Comment by NathanGRomano** [comment]
``` javascript
var io = require('socket.io')(5000);
var router = require('socket.io-events')();
router.on('ok', function (sock, args, next) {
  console.log('args', args);
  // if the client sends up a two, invoke the callback function which is in args[2].
  if (args[1] == '2') return args[2]('some other thing');
  next();
});
io.use(router);
io.on('connection', function (sock) {
  sock.on('ok', function (data, cb) {
      console.log('got data %s', data);
      cb('dog');
  }); 
});

setTimeout(function () {
  var sock = require('socket.io-client')('ws://localhost:5000');
  sock.on('connect', function () {
    sock.emit('ok', 1, function (data) {
      console.log('data', data);
    }); 
    sock.emit('ok', 2, function (data) {
      console.log('data 2', data);
    }); 
  }); 
  sock.on('ok', function () {
    console.log('ok');
  }); 
}, 1000);
```

**Comment by shopapps** [comment]
That's great thanks, I will test and let you know.  I did try console.log ing the args but couldn't see the callback in there..  maybe I just missed something..  thanks again.

**Comment by NathanGRomano** [comment]
Thanks for bringing this up.  If you have any other questions just ask.
